### PR TITLE
test api.GetArticle

### PR DESCRIPTION
**Pull request by vicky-sunshine**
Try to improve with a small step. 
- Test api.GetArticle

### CODE REVIEW

**Comment by vicky-sunshine** [comment]
Still need to figure out why the coverage phase failed at Test_GetUser and TestRegister where I didn't modify.

**Comment by chhsiao1981** [comment]
> Still need to figure out why the coverage phase failed at Test_GetUser and TestRegister where I didn't modify.

@vicky-sunshine ～

Basically tests passed in testing-stage.
There is some issue with shared-mem tests in that sometimes we can't correctly get shared-mem.
Rerunning the test again usually solves the issue.

**Comment by chhsiao1981** [comment]
@vicky-sunshine 

FYI

https://github.com/Ptt-official-app/go-pttbbs/issues/164

**Pull request merged**
